# Ditch sudo and use containers.
# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  include:
    # aliased to a recent 7.x version
    - php: 7.0
    # aliased to a recent 5.6.x version
    - php: 5.6
    # Current $required_php_version for WordPress: 5.2.4
    # aliased to 5.2.17
    - php: 5.2
    # aliased to a recent hhvm version
    - php: hhvm
    # aliased to a recent nightly version
    - php: nightly
  allow_failures:
    - php: nightly

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
  # Setup WP_TESTS_DIR (needed to bootstrap WP PHPUnit tests).
  - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit/
  # Clone the WordPress develop repo.
  - git clone --depth=1 --branch="4.3" git://develop.git.wordpress.org/ /tmp/wordpress/
  # Setup DB.
  - mysql -e "CREATE DATABASE wordpress_test;" -uroot
  # Setup wp-config.
  - cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" /tmp/wordpress/wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" /tmp/wordpress/wp-tests-config.php
  - sed -i "s/yourpasswordhere//" /tmp/wordpress/wp-tests-config.php

#install: composer install --no-dev

script:
  - phpunit

notifications:
  on_success: never
  on_failure: change

cache:
  directories:
    - vendor
    - $HOME/.composer/cache